---
title: "CSMFs 2019-2021 by World Region"
output:
  html_document:
    toc: true
    toc_float: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(ggplot2)
library(tidyverse)
library(flextable)
library(officer)
library(countrycode)
dat <- readRDS("C:/Users/HEilerts/Institute of International Programs Dropbox/Hallie Eilerts-Spinelli/CA-CODE/Comparison-CACODE-GHE/gen/rates.rds")
v_cod_order <- c("Measles", "Maternal", 
                 "Intrapartum", "Preterm","SepsisMening", "Tetanus", "MeningEnceph" ,
                 "HIV", "ARI","LRI",  "TB", "Diarrhoeal", "Malaria", "OtherCMPN",
                "Congenital", "Cardiovascular", "Digestive", "Neoplasms", "OtherNCD",
                "InterpVio","SelfHarm", "Drowning", "RTI", "OtherInj", "NatDis", "CollectVio",
                "COVID19","OtherCOVID19")
dat$COD <- factor(dat$COD, levels = v_cod_order)
dat$CountryName <- countrycode(dat$Name, origin = "iso3c", destination = "country.name")

```


```{r results="asis", eval = FALSE}
cat("
<style>
  /* Make the table scrollable and apply sticky header */
  .flextable {
    display: block;
    overflow: auto;
    max-height: 400px; /* Adjust height as needed */
    width: 100%;
  }
  
  .flextable thead {
    position: sticky;
    top: 0;
    background-color: white;
    z-index: 1; /* Make sure header is above table rows */
  }
</style>
")
```

# 2019

## 5-9y

```{r frac5to9_2019,  fig.height = 10, fig.width=14}
# fig.height = 8, fig.width=10
pnat <- dat %>%
  filter(!(COD %in% c("COVID19", "OtherCOVID19"))) %>%
  filter(AgeGroup %in% c("05to09y") & Sex == "Total" & Year == 2019 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "5-9y") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r frac5to9inc_2019, fig.height = 6, fig.width=8}
pnat <- dat %>%
  filter(!(COD %in% c("COVID19", "OtherCOVID19"))) %>%
  filter(AgeGroup %in% c("05to09y") & Sex == "Total" & Year == 2019 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "5-9y") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```

## 10-14y

```{r frac10to14_2019,  fig.height = 10, fig.width=14}
pnat <- dat %>%
    filter(!(COD %in% c("COVID19", "OtherCOVID19"))) %>%
  filter(AgeGroup %in% c("10to14y") & Sex == "Total" & Year == 2019 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "10-14y") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 

```

```{r frac10to14inc_2019, fig.height = 7, fig.width=9}
pnat <- dat %>%
    filter(!(COD %in% c("COVID19", "OtherCOVID19"))) %>%
  filter(AgeGroup %in% c("10to14y") & Sex == "Total" & Year == 2019 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "10-14y") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```

## 15-19y F

```{r frac15to19f_2019,  fig.height = 10, fig.width=14}
pnat <- dat %>%
    filter(!(COD %in% c("COVID19", "OtherCOVID19"))) %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Female" & Year == 2019 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yF") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r frac15to19Finc_2019, fig.height = 7, fig.width=9}
pnat <- dat %>%
    filter(!(COD %in% c("COVID19", "OtherCOVID19"))) %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Female" & Year == 2019 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yF") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```

## 15-19y M

```{r frac15to19m_2019, fig.height = 10, fig.width=14}
pnat <- dat %>%
    filter(!(COD %in% c("COVID19", "OtherCOVID19","Maternal"))) %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Male" & Year == 2019 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yM") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r frac15to19Minc_2019, fig.height = 7, fig.width=9}
pnat <- dat %>%
    filter(!(COD %in% c("COVID19", "OtherCOVID19","Maternal"))) %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Male" & Year == 2019 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yM") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```

## 15-19 T

```{r frac15to19t_2019, fig.height = 10, fig.width=14}
pnat <- dat %>%
    filter(!(COD %in% c("COVID19", "OtherCOVID19"))) %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Total" & Year == 2019 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19y T") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r frac15to19tinc_2019, fig.height = 7, fig.width=9}
pnat <- dat %>%
    filter(!(COD %in% c("COVID19", "OtherCOVID19"))) %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Total" & Year == 2019 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19y T") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```


# 2020

## 5-9y

```{r frac5to9_2020,  fig.height = 10, fig.width=14}
# fig.height = 8, fig.width=10
pnat <- dat %>%
  filter(AgeGroup %in% c("05to09y") & Sex == "Total" & Year == 2020 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "5-9y") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r frac5to9inc_2020, fig.height = 6, fig.width=8}
pnat <- dat %>%
  filter(AgeGroup %in% c("05to09y") & Sex == "Total" & Year == 2020 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "5-9y") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```

## 10-14y

```{r frac10to14_2020,  fig.height = 10, fig.width=14}
pnat <- dat %>%
  filter(AgeGroup %in% c("10to14y") & Sex == "Total" & Year == 2020 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "10-14y") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 

```

```{r frac10to14inc_2020, fig.height = 7, fig.width=9}
pnat <- dat %>%
  filter(AgeGroup %in% c("10to14y") & Sex == "Total" & Year == 2020 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "10-14y") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```

## 15-19y F

```{r frac15to19f_2020,  fig.height = 10, fig.width=14}
pnat <- dat %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Female" & Year == 2020 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yF") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r frac15to19Finc_2020, fig.height = 7, fig.width=9}
pnat <- dat %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Female" & Year == 2020 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yF") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```

## 15-19y M

```{r frac15to19m_2020, fig.height = 10, fig.width=14}
pnat <- dat %>%
   filter(!(COD %in% c("Maternal"))) %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Male" & Year == 2020 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yM") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r frac15to19Minc_2020, fig.height = 7, fig.width=9}
pnat <- dat %>%
  filter(!(COD %in% c("Maternal"))) %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Male" & Year == 2020 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yM") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```


# 2021

## 5-9y

```{r rate5to9_2021, fig.height = 10, fig.width=14, eval=FALSE}
pnat <- dat %>%
  filter(AgeGroup %in% c("05to09y") & Sex == "Total" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = rate_cacode, GHE = rate_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  ) %>% 
  mutate(value = value*1000) 
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="mx per 1,000", y= "",
        title = "5-9y 2021") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 

```

```{r rate10to14_2021, fig.height = 10, fig.width=14, eval=FALSE}
pnat <- dat %>%
  filter(AgeGroup %in% c("10to14y") & Sex == "Total" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = rate_cacode, GHE = rate_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  ) %>% 
  mutate(value = value*1000) 
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="mx per 1,000", y= "",
        title = "10-14y 2021") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 

```

```{r rate15to19f_2021, fig.height = 10, fig.width=14, eval=FALSE}
pnat <- dat %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Female" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = rate_cacode, GHE = rate_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  ) %>% 
  mutate(value = value*1000) 
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="mx per 1,000", y= "",
        title = "15-19yF 2021") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r rate15to19m_2021, fig.height = 10, fig.width=14, eval=FALSE}
pnat <- dat %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Male" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = rate_cacode, GHE = rate_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  ) %>% 
  mutate(value = value*1000) 
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="mx per 1,000", y= "",
        title = "15-19yM 2021") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r frac5to9, fig.height = 10, fig.width=14}
pnat <- dat %>%
  filter(AgeGroup %in% c("05to09y") & Sex == "Total" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "5-9y 2021") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 

```

```{r frac5to9inc_2021, fig.height = 6, fig.width=8}
pnat <- dat %>%
  filter(AgeGroup %in% c("05to09y") & Sex == "Total" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "5-9y") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```


## 10-14y

```{r frac10to14, fig.height = 10, fig.width=14}
pnat <- dat %>%
  filter(AgeGroup %in% c("10to14y") & Sex == "Total" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "10-14y 2021") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 

```

```{r frac10to14inc_2021, fig.height = 7, fig.width=9}
pnat <- dat %>%
  filter(AgeGroup %in% c("10to14y") & Sex == "Total" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "10-14y") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```


## 15-19y F

```{r frac15to19f, fig.height = 10, fig.width=14}
pnat <- dat %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Female" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yF 2021") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r frac15to19Finc_2021, fig.height = 7, fig.width=9}
pnat <- dat %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Female" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yF") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```


## 15-19y M

```{r frac15to19m, fig.height = 10, fig.width=14}
pnat <- dat %>%
  filter(!(COD %in% c("Maternal"))) %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Male" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yM 2021") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r frac15to19Minc_2021, fig.height = 7, fig.width=9}
pnat <- dat %>%
  filter(!(COD %in% c("Maternal"))) %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Male" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yM") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```


# COVID-19 in GHE

```{r covid20202021,  fig.height = 7, fig.width=6}
v_agegrp <- c("01to04y","05to09y","10to14y","15to19y")
pnat <- dat %>%
   filter(AgeGroup %in% v_agegrp) %>%
  filter(Year %in% c(2020, 2021) & AdminLevel %in% c("National") & COD %in% c("COVID19","OtherCOVID19"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  filter(Sex == "Total") %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "frac_ghe")))
p %>%
  ggplot() + 
  geom_boxplot(aes(x=frac_ghe, y = AgeGroup, fill =  COD), outliers = FALSE) +
  labs(x="CSMF", y= "") +
  theme_bw() +
  facet_grid(SDGregion~Year,
     labeller = label_wrap_gen(width = 2, multi_line = TRUE)) +
  theme(legend.direction = "horizontal", legend.position = "bottom",
        strip.text.y.right = element_text(angle = 0), text = element_text(size = 8)) 
```

```{r covid2020, eval =FALSE}
pnat <- dat %>%
  filter(Year %in% 2020 & AdminLevel %in% c("National") & COD %in% c("COVID19","OtherCOVID19"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  filter(Sex == "Total") %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "frac_ghe")))
p %>%
  ggplot() + 
  geom_boxplot(aes(x=frac_ghe, y = AgeGroup, fill =  COD), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "2020") +
  theme_bw() +
  facet_wrap(~SDGregion, ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r covid2021, eval =FALSE}
pnat <- dat %>%
  filter(Year %in% 2021 & AdminLevel %in% c("National") & COD %in% c("COVID19","OtherCOVID19"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  filter(Sex == "Total") %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "frac_ghe")))
p %>%
  ggplot() + 
  geom_boxplot(aes(x=frac_ghe, y = AgeGroup, fill =  COD), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "2021") +
  theme_bw() +
  facet_wrap(~SDGregion, ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

### Oceania

```{r tab5to9covidoceania}
#v_agegrp <- c("00to01m","01to11m","01to04y","05to09y","10to14y","15to19y","20to24y")
v_agegrp <- c("05to09y","10to14y","15to19y")
std_border <- fp_border(color = "gray")
dat %>%
  filter(AgeGroup %in% v_agegrp) %>%
  filter(Sex == "Total" & COD == "COVID19" & SDGregion == "Oceania" & Year %in% c(2020,2021) & Sex == "Total") %>%
  select(CountryName, Year, AgeGroup, total_dths, dths_ghe, frac_ghe, rate_ghe) %>%
  mutate(total_dths = ifelse(is.na(total_dths), 0, round(total_dths)),
         dths_ghe = ifelse(is.na(dths_ghe), 0, round(dths_ghe)),
         rate_ghe = round(rate_ghe*1000, 2)) %>%
  mutate(frac_ghe = paste0(formatC(100*dths_ghe/total_dths, 2, format="f"),"%"),) %>%
  pivot_wider(
    id_cols = c(CountryName, AgeGroup),
    names_from = Year,
    values_from = c(total_dths, dths_ghe, frac_ghe)
  ) %>%
  select(AgeGroup, CountryName, total_dths_2020, dths_ghe_2020, frac_ghe_2020,
         total_dths_2021, dths_ghe_2021, frac_ghe_2021) %>%
  mutate(AgeGroup = factor(AgeGroup, levels = v_agegrp)) %>%
  arrange(AgeGroup, CountryName) %>%
  # Recalculating fraction so that it is the same as the rounded deaths/rounded total
  # Otherwise wouldn't match
  flextable()  %>% align(j=3:8, align="center", part="all") %>%
  merge_v(., j = ~ AgeGroup) %>%
  hline(., part = "all", border = std_border) %>%
  set_header_labels(., CountryName = "Country", total_dths_2020 = "Total deaths",
                    total_dths_2021 = "Total deaths",
                    dths_ghe_2020 = "COVID deaths", dths_ghe_2021 = "COVID deaths", 
                    frac_ghe_2020 = "CSMF",  frac_ghe_2021 = "CSMF") %>%
  fontsize(size = 8, part = "all") %>%
  add_header_row(., values = c("","2020", "2021"),
                  colwidths = c(2,3,3))
```

```{r fracAusNzl_2019,  fig.height = 7, fig.width=9, eval = FALSE}
# fig.height = 8, fig.width=10
v_agegrp <- c("05to09y","10to14y","15to19y")
dat %>%
  filter(AgeGroup %in% v_agegrp) %>%
  filter(!(COD %in% c("COVID19", "OtherCOVID19"))) %>%
  filter(Sex == "Total" & Year %in% 2019:2021 & 
           AdminLevel %in% c("National") & SDGregion == "Australia and New Zealand") %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  ) %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "", title = "2019-2021") +
  theme_bw() +
  facet_grid(Name~AgeGroup) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 

dat %>%
  filter(AgeGroup %in% v_agegrp) %>%
  filter(!(COD %in% c("COVID19", "OtherCOVID19"))) %>%
  filter(Sex == "Total" & Year %in% 2019:2021 & 
           AdminLevel %in% c("National") & SDGregion == "Australia and New Zealand") %>%
  filter(COD == "OtherCMPN" & Name == "NZL")
```
