---
title: "CA CODE and GHE CSMF Comparison"
subtitle: "Box plots for 2021 by world region"
output:
  html_document:
    toc: true
    toc_float: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(ggplot2)
library(tidyverse)
library(flextable)
library(officer)
library(countrycode)
dat <- readRDS("C:/Users/HEilerts/Institute of International Programs Dropbox/Hallie Eilerts-Spinelli/CA-CODE/Comparison-CACODE-GHE/gen/rates.rds")
v_cod_order <- c("Measles", "Maternal", 
                 "Intrapartum", "Preterm","SepsisMening", "Tetanus", "MeningEnceph" ,
                 "HIV", "ARI","LRI",  "TB", "Diarrhoeal", "Malaria", "OtherCMPN",
                "Congenital", "Cardiovascular", "Digestive", "Neoplasms", "OtherNCD",
                "InterpVio","SelfHarm", "Drowning", "RTI", "OtherInj", "NatDis", "CollectVio",
                "COVID19","OtherCOVID19")
dat$COD <- factor(dat$COD, levels = v_cod_order)
dat$CountryName <- countrycode(dat$Name, origin = "iso3c", destination = "country.name")
```

# COVID-19 in GHE

```{r covid20202021,  fig.height = 7, fig.width=6}
v_agegrp <- c("01to04y","05to09y","10to14y","15to19y")
pnat <- dat %>%
   filter(AgeGroup %in% v_agegrp) %>%
  filter(Year %in% c(2020, 2021) & AdminLevel %in% c("National") & COD %in% c("COVID19","OtherCOVID19"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  filter(Sex == "Total") %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "frac_ghe")))
p %>%
  ggplot() + 
  geom_boxplot(aes(x=frac_ghe, y = AgeGroup, fill =  COD), outliers = FALSE) +
  labs(x="CSMF", y= "") +
  theme_bw() +
  facet_grid(SDGregion~Year,
     labeller = label_wrap_gen(width = 2, multi_line = TRUE)) +
  theme(legend.direction = "horizontal", legend.position = "bottom",
        strip.text.y.right = element_text(angle = 0), text = element_text(size = 8)) 
```

# 5-9y

```{r frac5to9, fig.height = 10, fig.width=14}
pnat <- dat %>%
  filter(AgeGroup %in% c("05to09y") & Sex == "Total" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "5-9y 2021") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 

```

```{r frac5to9inc_2021, fig.height = 6, fig.width=8}
pnat <- dat %>%
  filter(AgeGroup %in% c("05to09y") & Sex == "Total" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "5-9y") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```

# 10-14y

```{r frac10to14, fig.height = 10, fig.width=14}
pnat <- dat %>%
  filter(AgeGroup %in% c("10to14y") & Sex == "Total" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "10-14y 2021") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 

```

```{r frac10to14inc_2021, fig.height = 7, fig.width=9}
pnat <- dat %>%
  filter(AgeGroup %in% c("10to14y") & Sex == "Total" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "10-14y") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```

# 15-19y F

```{r frac15to19f, fig.height = 10, fig.width=14}
pnat <- dat %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Female" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yF 2021") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r frac15to19Finc_2021, fig.height = 7, fig.width=9}
pnat <- dat %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Female" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yF") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```

# 15-19y M

```{r frac15to19m, fig.height = 10, fig.width=14}
pnat <- dat %>%
  filter(!(COD %in% c("Maternal"))) %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Male" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","SDGregion","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yM 2021") +
  theme_bw() +
  facet_wrap(~SDGregion, scales = "free", ncol = 3) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom") 
```

```{r frac15to19Minc_2021, fig.height = 7, fig.width=9}
pnat <- dat %>%
  filter(!(COD %in% c("Maternal"))) %>%
  filter(AgeGroup %in% c("15to19y") & Sex == "Male" & Year == 2021 & 
           AdminLevel %in% c("National"))
pworld <- pnat %>%
  mutate(Name = "World",
         SDGregion = "World")
p <- rbind(pworld, pnat)
p <- p %>%
  mutate(CACODE = frac_cacode, GHE = frac_ghe) %>%
  select(all_of(c("AgeGroup","AdminLevel","Name","wbinc13","Sex","Year", "COD", "CACODE","GHE"))) %>% 
  pivot_longer(
    cols = all_of(c("CACODE","GHE")),
    names_to = "Source"
  )
p %>%
  ggplot() + 
  geom_boxplot(aes(x=value, y = COD, fill =  Source), outliers = FALSE) +
  labs(x="CSMF", y= "",
        title = "15-19yM") +
  theme_bw() +
  facet_wrap(~wbinc13, scales = "free", ncol = 2) +
  scale_fill_manual(values = c("#8C2981FF","#FA7F5EFF"), name = "") + 
  theme(legend.direction = "horizontal", legend.position = "bottom")  + 
  theme(legend.direction = "horizontal", legend.position = "bottom", text =  element_text(size = 8)) 
```
